# Generated by Django 4.2.18 on 2025-01-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AddField(
            model_name='page',
            name='is_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('home.html', 'Homepage'), ('default.html', 'Default Page'), ('news.html', 'News Page'), ('program.html', 'Program Page'), ('profile.html', 'Profile Page'), ('admission.html', 'Admission Page'), ('scholarship.html', 'Scholarship Page')], default='default.html', max_length=100),
        ),
    ]
