# Generated by Django 4.2.18 on 2025-01-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_articlecategory_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO keywords (comma-separated)', max_length=255),
        ),
    ]
